#!/bin/bash

set -euo pipefail

pkgs=(
    build-essential
    curl
    gfortran
    git
    libssl-dev
    openssl
    pkg-config
    python3
    python3-dev
    python3-pip
    python3-venv
    autoconf
    automake
    libtool
    cython3
)

pdf_sets=(
    NNPDF40_nnlo_as_01180
    MSHT20qed_an3lo
    CT18NNLO_as_0118
    NNPDF40_nnlo_as_01160
    NNPDF40_an3lo_as_01180_qed_mhou
    EPPS21nlo_CT18Anlo_Fe56
    MAPFF10NLOPIsum
    NNPDFpol20_nnlo_as_01180
)

neopdf_sets=(
    NNPDF40_nnlo_as_01180
    nNNPDF30_nlo_as_0118
)

apt update
apt install -y "${pkgs[@]}"

# link cython to cython3
ln -s /usr/bin/cython3 /usr/local/bin/cython

# install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y

for version in ${RUST_V}; do
    # the last command will be the default
    rustup install "${version}" --profile minimal
    rustup default "${version}"
    # install LLVM tools needed for code coverage
    rustup component add llvm-tools
done

# install cargo-c needed for the CAPI
cargo install --locked cargo-c --version "${CARGOC_V}"

# remove files generated by cargo
rm -r /usr/local/cargo/registry

# install LHAPDF
curl -L "https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${LHAPDF_V}.tar.gz" | tar xzf -
cd "LHAPDF-${LHAPDF_V}"
autoreconf -f -i
PYTHON=$(which python3) ./configure --prefix=/usr --enable-python
touch wrappers/python/lhapdf.pyx
make -j V=1
make install
ldconfig
# Verify the Python module was installed
bash -c "lhapdf-config --datadir"
python3 -c "import sys; print(sys.path)"
python3 -c "import lhapdf; print('LHAPDF imported successfully')"
cd ..

# install PDF sets
for pdf in "${pdf_sets[@]}"; do
    # see the following link why `--no-same-owner` may be necessary:
    # https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233
    curl "https://lhapdfsets.web.cern.ch/current/${pdf}.tar.gz" | tar xzf - --no-same-owner -C /usr/share/LHAPDF
done

# Download NeoPDF sets
for neo in "${neopdf_sets[@]}"; do
    wget --no-verbose --no-clobber -P /usr/share/LHAPDF "https://data.nnpdf.science/neopdf/data/${neo}.neopdf.lz4"
done
